# Generated by Django 5.1.4 on 2025-01-27 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_mailing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MailingModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "start",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="дата и время первой отправки"
                    ),
                ),
                (
                    "end",
                    models.DateTimeField(
                        verbose_name="дата и время окончания отправки"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=9, verbose_name="статус рассылки"),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_mailing.messagemodel",
                        verbose_name="сообщения для отправки",
                    ),
                ),
                (
                    "recipients",
                    models.ManyToManyField(
                        to="web_mailing.clientmodel", verbose_name="получатели"
                    ),
                ),
            ],
            options={
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
                "ordering": ["start", "end"],
            },
        ),
        migrations.CreateModel(
            name="MailingAttemptModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attempt_start",
                    models.DateTimeField(
                        auto_now=True, verbose_name="дата и время попытки"
                    ),
                ),
                (
                    "status",
                    models.CharField(max_length=10, verbose_name="статус рассылки"),
                ),
                (
                    "server_feedback",
                    models.CharField(
                        max_length=100, verbose_name="ответ почтового сервера"
                    ),
                ),
                (
                    "mailing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="web_mailing.mailingmodel",
                        verbose_name="рассылка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Попытка рассылки",
                "verbose_name_plural": "Попытки рассылок",
                "ordering": ["attempt_start"],
            },
        ),
    ]
