# Generated by Django 5.1.4 on 2025-02-02 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_mailing", "0002_mailingmodel_mailingattemptmodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattemptmodel",
            name="status",
            field=models.CharField(
                choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                verbose_name="статус попытки",
            ),
        ),
        migrations.AlterField(
            model_name="mailingmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Начата", "Начата"),
                    ("Окончена", "Окончена"),
                ],
                verbose_name="статус рассылки",
            ),
        ),
    ]
