# Generated by Django 5.1.4 on 2025-02-28 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_mailing", "0003_alter_mailingattemptmodel_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingmodel",
            name="end",
            field=models.DateTimeField(
                null=True, verbose_name="дата и время окончания отправки"
            ),
        ),
        migrations.AlterField(
            model_name="mailingmodel",
            name="start",
            field=models.DateTimeField(
                null=True, verbose_name="дата и время первой отправки"
            ),
        ),
    ]
