# Generated by Django 5.1.4 on 2025-03-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_mailing", "0004_alter_mailingmodel_end_alter_mailingmodel_start"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingmodel",
            name="status",
            field=models.CharField(
                choices=[
                    ("Создана", "Создана"),
                    ("Начата", "Начата"),
                    ("Окончена", "Окончена"),
                ],
                default="Создана",
                verbose_name="статус рассылки",
            ),
        ),
    ]
