# Generated by Django 5.1.4 on 2025-03-06 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web_mailing", "0005_alter_mailingmodel_status"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="clientmodel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_client",
                to=settings.AUTH_USER_MODEL,
                verbose_name="клиент пользователя",
            ),
        ),
        migrations.AddField(
            model_name="messagemodel",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="users_message",
                to=settings.AUTH_USER_MODEL,
                verbose_name="сообщения пользователя",
            ),
        ),
    ]
