# Generated by Django 5.1.4 on 2025-03-08 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("web_mailing", "0007_mailingmodel_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmodel",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_object", "can view object")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingmodel",
            options={
                "ordering": ["start", "end"],
                "permissions": [
                    ("can_view_object", "can view object"),
                    ("can_disable_mailing", "can disable mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="messagemodel",
            options={
                "ordering": ["title"],
                "permissions": [("can_view_object", "can view object")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
