# Generated by Django 5.1.4 on 2025-03-08 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_mailing",
            "0008_alter_clientmodel_options_alter_mailingmodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientmodel",
            options={
                "ordering": ["full_name"],
                "permissions": [("can_view_client", "can view client")],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingmodel",
            options={
                "ordering": ["start", "end"],
                "permissions": [
                    ("can_view_mailing", "can view mailing"),
                    ("can_disable_mailing", "can disable mailing"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="messagemodel",
            options={
                "ordering": ["title"],
                "permissions": [("can_view_message", "can view message")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
