# Generated by Django 5.1.4 on 2025-03-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "web_mailing",
            "0009_alter_clientmodel_options_alter_mailingmodel_options_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingattemptmodel",
            name="server_feedback",
            field=models.CharField(
                max_length=500, verbose_name="ответ почтового сервера"
            ),
        ),
    ]
